name: Auto-Merge
on:
  pull_request_target:
    types: [labeled]

permissions:
  pull-requests: read
  contents: write

jobs:
  enable-auto-merge:
    runs-on: ubuntu-24.04

    if: github.event.pull_request.user.login == 'bb-17[bot]' && contains(github.event.pull_request.labels.*.name, 'auto-merge')
    steps:
      - uses: alexwilson/enable-github-automerge-action@2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
