---
name: 'Renovate'

on:
  workflow_dispatch:

  schedule:
    - cron: '2 * * * *' # Every hour (2min past the hour)
  push:
    branches: ['main']
    paths:
      - .github/renovate.json

permissions:
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  LOG_LEVEL: 'debug'
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: '${{ github.repository }}'
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
  RENOVATE_GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  RENOVATE_BOT_NAME: 'bb-17'

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-24.04
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@v2.2.0
        id: app-token
        with:
          app-id: '${{ secrets.BOT_APP_ID }}'
          private-key: '${{ secrets.BOT_PRIVATE_KEY }}'

      - name: Checkout
        uses: actions/checkout@v6.0.0
        with:
          token: '${{ steps.app-token.outputs.token }}'

      - name: Renovate
        uses: renovatebot/github-action@v44.0.4
        with:
          configurationFile: .github/renovate.json
          token: '${{ steps.app-token.outputs.token }}'
